# Generated by Django 5.2.5 on 2025-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='book_photos/default.webp', upload_to='book_photos', verbose_name='photo'),
            preserve_default=False,
        ),
    ]
